### ISSUE TITLE
Consider re-licensing to MPL

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/kstat-rs#2]
This would bring the crate more in-line with other Oxide software, which is largely MPL.

**Comment by jclulow** [comment]
FWIW, I think we probably want to keep library crates as **(MIT OR Apache-2.0)** to fit in with the broader Rust ecosystem.  That's what I just did with [ucred-rs](https://github.com/illumos/ucred-rs) which is a similar wrapper.

**Comment by bnaecker** [comment]
Added MPL OR Apache-2.0 in 5d75026742b8c79564dbfc48e3f3024fe05e2a1f
